# В api cataas.com не все указанные теги являются реальными (по многим приходит ответ 404). Пришлось проверить все
# (программно, конечно) и сохранить действительные теги здесь
real_tags = ['Black', 'Cat', 'Cute', 'Hiding', 'Lay', 'Luz', 'Outside', 'Summer', 'White', 'advent-calendar-2016',
             'alcoholic',
             'ange', 'angry', 'attack', 'attention', 'baby', 'basket', 'bath', 'beautiful', 'bed', 'belly', 'big',
             'big-eyes',
             'bigfloppa', 'biscuit', 'black', 'blanket', 'blep', 'blurred', 'bombay', 'box', 'bread', 'breast', 'brown',
             'bubble',
             'calico', 'cash', 'cat', 'cat_winston', 'cats', 'chair', 'chill', 'christmas', 'close', 'closeup', 'comfy',
             'computer',
             'confused', 'cool', 'costume', 'couch', 'crazy', 'cuddle', 'cuddles', 'cup', 'curl', 'cute', 'daisy',
             'dance',
             'derp',
             'dev', 'didizin', 'disappointed', 'dj', 'drink', 'duo', 'ears', 'evil', 'excited', 'exferal', 'eyes',
             'facecat',
             'fail', 'fall', 'fat', 'feeding', 'female', 'fight', 'fluffy', 'flying', 'food', 'fun', 'funny', 'gamer',
             'gif',
             'ginger', 'glass', 'gray', 'grumpy', 'hairless', 'halloween', 'hard', 'hat', 'hello', 'hug', 'hulu',
             'jump',
             'jumping',
             'kitten', 'kitty', 'lay', 'laying', 'lick', 'loaf', 'looking', 'mask', 'meme', 'menacing', 'meow', 'money',
             'multiple_colors', 'nelut', 'no', 'nope', 'nyancat', 'orange', 'outside', 'party', 'petting', 'pingu',
             'pino',
             'play',
             'resting', 'roll', 'sad', 'sara', 'scared', 'selfie', 'several', 'shocked', 'siamese', 'silly', 'sing',
             'sit',
             'sleep',
             'sleeping', 'sleepy', 'small', 'smol', 'snow', 'sofa', 'soon', 'stare', 'stip', 'stripes', 'stuck', 'sws',
             'tabby',
             'table', 'tinny', 'tired', 'tongue', 'trapped', 'tree', 'trump', 'tux', 'tuxedo', 'two', 'ugly', 'white',
             'white_fur',
             'window', 'witch', 'wtf', 'yawn', 'zusia']
